---
- name: create lxc
  hosts: proxmox
  vars:
    api_pass: "W@rcraft"
#  vars_prompt: 
#    - name: lxc_name
#      prompt: please enter the target host name
#      private: no
#
#    - name: lxc_pass
#      prompt: please enter the target host root passsword
#      private: yes
#
#    - name: lxc_ip
#      prompt: please enter the target host ip
#      private: no
#
#    - name: api_pass
#      prompt: please enter the proxmox password
#      private: yes

  tasks:
  - name: get ip address
    script: lxc_param.sh
    delegate_to: localhost
    register: lxc_ip
   
  - name: create lxc 
    proxmox:
      node: pve01
      api_user: root@pam
      api_password: "{{ api_pass }}"
      api_host: "{{ ansible_host }}"
      hostname: "{{ lxc_ip.stdout_lines[0] }}"
      ostemplate: 'local:vztmpl/centos-7-x86_64.tar.gz'
      netif: '{"net0":"name=eth0,gw=192.168.90.1,ip={{ lxc_ip.stdout_lines[0] }}/24,bridge=vmbr0"}'
      nameserver: "8.8.8.8"
      password: "P@ssw0rd"
      pool: "ansible"
      pubkey: "{{ lookup('file', 'id_rsa/id_rsa.pub') }}"
      storage: "data"
      disk: "4"
      cores: 1
      memory: "256"
      unprivileged: "yes"
