---
- name: update system
  hosts: linux_servers

  tasks:
  - name: update Centos
    yum: update_only=yes
    when: ansible_os_family=="RedHat"

  - name: Update Debian
    apt: update_cache=yes
    when: ansible_os_family=="Debian"
